# ======================== Elasticsearch Configuration =========================
#

cluster.name: dotCMSContentIndex

transport:
    host: 127.0.0.1
    tcp.port: 9300
    tcp.connect_timeout: 2s

discovery.zen:

    minimum_master_nodes: 1
    ping_timeout: 3s
    join_timeout: 6s
    fd:
        ping_timeout: 3s
        ping_interval: 1s
        ping_retries: 3



path:
    data: /data/local/esdata
    repo: /data/local/essnapshot/snapshots
    logs: /data/local/logs

http:
    enabled: false
    cors.enabled: false
    port: 9200
    host: 127.0.0.1

indices.query.bool.max_clause_count: 10240
search.default_search_timeout: 30s
search.low_level_cancellation: true
